[package]
name = "panel"
version = "0.0.2"
edition = "2021"
license = "MIT"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
gloo = { version = "0.10.0" }
yew = { version = "0.21.0", features = ["csr"] }
js-sys = { version = "0.3.64" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.107" }
serde-wasm-bindgen = "=0.6.0"
wasm-bindgen = { version = "0.2.87" }
web-sys = { version = "0.3.64" }
