# TailwindCss
terminal-1:
    @./tailwindcss -i ./input.css -o ./output.css --watch

# Watch app Frontend
terminal-2:
    @watchexec --watch ./app  --no-vcs-ignore --restart --clear --exts rs wasm-pack build --target web --no-typescript --mode force --dev --out-name index --out-dir ../wasm ./app

# Vite bundler in dev
terminal-3:
    @npm run dev
