[package]
name = "background"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "=1.0.189", features = ["derive"] }
serde-wasm-bindgen = "=0.6.0"
wasm-bindgen = { version = "=0.2.87", features = ["serde-serialize"] }
web-sys = { version = "=0.3.64", features = ['console'] }
